"$schema": http://json-schema.org/draft-07/schema#
title: Zarr Array Metadata
type: object
properties:
  chunks:
    type: array
    items:
      type: integer
    minItems: 1
  compressor:
    type: object
    properties:
      id:
        type: string
      cname:
        type: string
      clevel:
        type: integer
      shuffle:
        type: integer
    required:
    - id
  dtype:
    type: object
  fill_value:
    type: object
  filters:
    type: array
    items:
      type: object
      properties:
        id:
          type: string
        dtype:
          type: string
        astype:
          type: string
      required:
      - id
  order:
    type: string
    enum: ["C", "F"]
  shape:
    type: array
    items:
      type: integer
    minItems: 1
  zarr_format:
    type: integer
required:
- chunks
- compressor
- dtype
- fill_value
- filters
- order
- shape
- zarr_format