"$schema": http://json-schema.org/draft-07/schema#
title: A CoverageJSON object
description: 'Component of OGC Coverage Implementation Schema 1.0. Last updated: 2023-05-10.
  Copyright (c) 2023 Open Geospatial Consortium, Inc. All Rights Reserved. To obtain
  additional rights of use, visit http://www.opengeospatial.org/legal/.'
$ref: ../coverageJSON/schema.yaml
