identifier-prefix: ogc.hosted.iliad.api.features.

name: ILIAD API Profiles
abstract: (Under construction) - defines and demonstrates a reusable mechanism for specialisation of OGC APIs using the Oceans Information Model (OIM) for semantic interoperability.
description: |
  Each building block defines a profile of a data exchange schema based on OGC API responses, mapped to the OIM using JSON-LD contexts. Common patterns are factored into reusable foundations to simplify development and maximise interoperability of such profiles, in a way which is scalable across future application requirements. 
  
  Thus, a pilot project to monitor Jellyfish swarms using Citizen Science will reuse common patterns for Citizen Science observations, which in turn we reuse a common pattern for observations, using an underlying component of the OIM - the OGC Observations model (SOSA ontology). 

schema-mapping:
  default: https://opengeospatial.github.io/bblocks/annotated-schemas/

imports:
  - default
  - https://opengeospatial.github.io/ogcapi-sosa/build/register.json
  - https://ogcincubator.github.io/geodcat-ogcapi-records/build/register.json
#   - https://ogcincubator.github.io/oceans-info-model/build/register.json
  
