"""Lightweight smoke test — imports + core paths that don't need pandas/pyarrow/xarray."""
import json
import sys
import tempfile
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent.parent))

from checkin.core import bblock_index, bblock_match, sniff, transformer_runner, vocab_index, vocab_match
from checkin.core import bblock_writer
from checkin.core.profile import Profile, PropertySpec


def test_sniff_csv_path():
    with tempfile.NamedTemporaryFile("w", suffix=".csv", delete=False) as f:
        f.write("id,lon,lat,time,species,count\n1,12.5,55.3,2026-03-12T10:05:00Z,Aurelia aurita,7\n")
        path = f.name
    r = sniff.sniff(path)
    assert r.format == "csv", r
    print("  sniff csv ok:", r.format)
    return path


def test_sniff_url_ogc():
    r = sniff._sniff_ogc_url("https://example.org/geoserver/wfs?service=WFS&request=GetCapabilities")
    assert r == "ogc-wfs", r
    print("  sniff ogc-wfs ok")


def test_bblock_index():
    entries = bblock_index.load_index()
    ids = [e.id for e in entries]
    assert "macroobservation" in ids, ids
    print(f"  bblock index loaded {len(entries)} bblocks; sample: {ids[:3]}")
    # Ensure property extraction worked for at least one
    macro = next(e for e in entries if e.id == "macroobservation")
    assert len(macro.properties) > 0, "no properties extracted"
    print(f"    macroobservation properties: {macro.properties[:6]}")
    return entries


def test_vocab_index():
    idx = vocab_index.build_index()
    s = vocab_index.summary(idx)
    print("  vocab index summary:", s)
    assert s["total"] > 0
    assert s["distinct_terms"] > 0
    return idx


def test_bblock_match(entries):
    p = Profile(format="csv", source="fake")
    p.properties = [PropertySpec(name=n) for n in ["species", "abundance", "depth_m", "salinity_psu", "lat", "lon", "time"]]
    ranked = bblock_match.rank(p, entries, k=5)
    print("  top matches:")
    for m in ranked[:3]:
        print(f"    {m.score:.3f} {m.entry.id} — {m.reason} — {m.matched_properties[:4]}")
    assert ranked[0].entry.id in {"macroobservation", "iliad-jellyfish-features"}, ranked[0].entry.id


def test_vocab_match(idx):
    cands = vocab_match.match_one("species", idx, k=3)
    print(f"  vocab 'species' candidates: {[(c.label or c.term, c.uri[:60]) for c in cands]}")


def test_transformer_json_to_geojson():
    lib = transformer_runner.load_library()
    spec = next(s for s in lib if s.id == "json-to-json-feature")
    rec = {"id": "obs-1", "longitude": 12.5, "latitude": 55.3, "species": "Aurelia aurita", "count": 7}
    result = transformer_runner.run(spec, rec, {"lon_field": "longitude", "lat_field": "latitude", "id_field": "id"})
    assert result.ok, result.errors + result.validation_errors
    assert result.output["type"] == "Feature"
    print(f"  json-to-json-feature ok; bbox-ish coords: {result.output['geometry']['coordinates']}")


def test_transformer_csv_to_stac():
    lib = transformer_runner.load_library()
    spec = next(s for s in lib if s.id == "csv-to-stac-item")
    row = {"id": "r1", "lon": "12.5", "lat": "55.3", "time": "2026-03-12T10:05:00Z", "species": "Aurelia aurita", "count": "7"}
    result = transformer_runner.run(spec, row, {"lon_field": "lon", "lat_field": "lat", "time_field": "time", "id_field": "id"})
    assert result.ok, result.errors + result.validation_errors
    out = result.output
    assert out["stac_version"] == "1.0.0"
    assert out["properties"]["datetime"] == "2026-03-12T10:05:00Z"
    print(f"  csv-to-stac-item ok: {out['id']}")


def test_bblock_writer():
    ack = [bblock_writer.AcknowledgedMapping(property_name="species", uri="http://rs.tdwg.org/dwc/terms/scientificName", source="macroobservation")]
    from checkin import STAGING_DIR
    lib = transformer_runner.load_library()
    spec = next(s for s in lib if s.id == "csv-to-stac-item")
    draft = bblock_writer.BBlockDraft(
        id="smoke-test-bb",
        title="Smoke Test BB",
        abstract="Generated by smoke test.",
        tags=["csv", "checkin"],
        depends_on=["macroobservation"],
        property_mappings=ack,
        sample_feature={"type": "Feature", "geometry": {"type": "Point", "coordinates": [12.5, 55.3]}, "properties": {"species": "Aurelia aurita"}},
        source_endpoint={"title": "sample csv", "local_path": "/tmp/sample.csv"},
        transformer_kind="library",
        transformer=spec,
        transformer_params={"lon_field": "lon", "lat_field": "lat", "time_field": "time"},
    )
    target = bblock_writer.write_staged(draft, overwrite=True)
    print(f"  staged → {target}")
    assert (target / "bblock.json").exists()
    assert (target / "context.jsonld").exists()
    assert (target / "transforms" / "transform.ref.json").exists()
    # Cleanup
    import shutil
    shutil.rmtree(target)


if __name__ == "__main__":
    print("== sniff ==")
    csv_path = test_sniff_csv_path()
    test_sniff_url_ogc()
    print("== bblock index ==")
    entries = test_bblock_index()
    print("== vocab index ==")
    idx = test_vocab_index()
    print("== bblock match ==")
    test_bblock_match(entries)
    print("== vocab match ==")
    test_vocab_match(idx)
    print("== transformers ==")
    test_transformer_json_to_geojson()
    test_transformer_csv_to_stac()
    print("== writer ==")
    test_bblock_writer()
    print("\nALL SMOKE TESTS PASSED")
