"$schema": https://json-schema.org/draft/2020-12/schema
description: 'Schemas for Ocean Information Model Observations'
$defs:
  OIMObsProps:
    allOf:
    - $ref: '../oim-obs-cs/schema.yaml#/$defs/OIMObsProps'
    - properties:
        hasResult:
          type: object
          properties:
            individualCount:
              type: integer
            organismQuantity:
              type: string
            organismQuantityType:
              type: string
            sampleSizeUnit:
              type: string
            sampleSizeValue:
              type: string
            densityOfJellyFish:
              type: string
              enum: [None, Some, Swarm, Few]
            stingByJellyFish:
              type: string
            strandedJellyFish:
              type: string

#              "aphiaID": "https://marinespecies.org/aphia.php?p=taxdetails&id=232032",

#              "sampleSizeValue": "11-30",
#              "scientificName": "Rhopilema nomadica",
#              "scientificNameID": "https://marinespecies.org/aphia.php?p=taxdetails&id=232032",

  OIMObsFeature:
    allOf:
    - $ref: '../oim-obs-cs/schema.yaml#/$defs/OIMObsFeature'
    - properties:
        properties:
          $ref: '#/$defs/OIMObsProps'
  OIMObsCollection:
    allOf:
    - $ref: '../oim-obs-cs/schema.yaml#/$defs/OIMObsCollection'
    - properties:
        features:
          type: array
          items:
            allOf:
              - $ref: '#/$defs/OIMObsFeature'
anyOf:
- $ref: '#/$defs/OIMObsProps'
- $ref: '#/$defs/OIMObsFeature'
- $ref: '#/$defs/OIMObsCollection'