"$schema": https://json-schema.org/draft/2020-12/schema
description: 'Schemas for Ocean Information Model Observations'
comment: This is a stub for now - with simple proxies for each object where schemas can be specialised.
$defs:
  OIMObsProps:
    allOf:
    - $ref: 'bblocks://ogc.hosted.iliad.api.features.oim-obs#/$defs/OIMObsProps'
      #aphiaID": "https://marinespecies.org/aphia.php?p=taxdetails&id=232032",

    - properties:
        sampleSizeValue:
          type: string
        scientificName:
          type: string
        scientificNameID:
          $ref: 'bblocks://ogc.ogc-utils.iri-or-curie'
        wormsConcept:
          type: string
          pattern: '^https://marinespecies\.org/.*'
        aphiaID:
          type: string
          pattern: '^https://marinespecies\.org/.*'
  OIMObsFeature:
    allOf:
    - $ref: 'bblocks://ogc.hosted.iliad.api.features.oim-obs#/$defs/OIMObsFeature'
    - properties:
        properties:
          $ref: '#/$defs/OIMObsProps'
  OIMObsCollection:
    allOf:
    - $ref: 'bblocks://ogc.hosted.iliad.api.features.oim-obs#/$defs/OIMObsCollection'
    - properties:
        features:
          type: array
          items:
            allOf:
              - $ref: '#/$defs/OIMObsFeature'
anyOf:
- $ref: '#/$defs/OIMObsProps'
- $ref: '#/$defs/OIMObsFeature'
- $ref: '#/$defs/OIMObsCollection'