"$schema": https://json-schema.org/draft/2020-12/schema
title: A OIM aligned STA Observation schema
description: 'Component of OGC STA Observation. no particular added constraints are added'
aalOf:
  - $ref: bblocks://ogc.api.sta.Observation
  # additional constraints that can be introduced at the schema level.
  # note SHACL rules may be required for more complex constrain logic.