"$schema": https://json-schema.org/draft/2020-12/schema
description: 'Schemas for Ocean Information Model Observations'
$defs:
  OIMObsProps:
    allOf:
    - $ref: '../oim-obs-cs/schema.yaml#/$defs/OIMObsProps'
    - properties:
        hasResult:
          type: object
          properties:
            quantityOfJF:
              type: integer
            densityOfJF:
              type: string
              enum: [None, Some, Swarm, Few]
            stingByJF:
              type: string
            beachedJF:
              type: string
        hasFeatureOfInterest:
          $ref: bblocks://ogc.ogc-utils.iri-or-curie
  OIMObsFeature:
    allOf:
    - $ref: '../oim-obs-cs/schema.yaml#/$defs/OIMObsFeature'
    - properties:
        properties:
          $ref: '#/$defs/OIMObsProps'
  OIMObsCollection:
    allOf:
    - $ref: '../oim-obs-cs/schema.yaml#/$defs/OIMObsCollection'
    - properties:
        features:
          type: array
          items:
            allOf:
              - $ref: '#/$defs/OIMObsFeature'
anyOf:
- $ref: '#/$defs/OIMObsProps'
- $ref: '#/$defs/OIMObsFeature'
- $ref: '#/$defs/OIMObsCollection'