"$schema": https://json-schema.org/draft/2020-12/schema
description: 'Schemas for Observations'
$defs:
  OIMObsProps:
    allOf:
    - $ref: bblocks://ogc.sosa.properties.observation
    - properties:
        label:
          oneOf:
            - type: string
            - type: object
  OIMObsFeature:
    allOf:
    - $ref: bblocks://ogc.sosa.features.observation
    - properties:
        properties:
          $ref: '#/$defs/OIMObsProps'
        observedProperty:
          $ref: bblocks://ogc.ogc-utils.iri-or-curie
  OIMObsCollection:
    allOf:
    - $ref: bblocks://ogc.sosa.features.observationCollection
    - properties:
        features:
          type: array
          items:
            allOf:
              - $ref: '#/$defs/OIMObsFeature'
anyOf:
- $ref: '#/$defs/OIMObsProps'
- $ref: '#/$defs/OIMObsFeature'
- $ref: '#/$defs/OIMObsCollection'