"$schema": http://json-schema.org/draft-07/schema#
title: Zarr Attributes Metadata
type: object
properties:
  long_name:
    type: string
  standard_name:
    type: string
  units:
    type: string
    enum:
    - degrees_north
    - degreesN
  _ARRAY_DIMENSIONS:
    type: array
    items:
      type: string
  "Conventions":
    "type": "string"
  "units_metadata":
    "type": "string"
  "cell_methods":
    "type": "string"
  "created_by":
    "type": "string"
  "date":
    "type": "string"
  "crs_wkt":
    "type": "string"
  "geotransform":
    "type": "string"
  "proj4": 
    "type": "string"
  "spatial_ref": 
    "type": "string"
required: #there are varios constraints depending on the position of the file, potentially these could be profiles of the bb, but there are no common names reqiured between root and group attributes
#- long_name
#- standard_name
#- units
#- _ARRAY_DIMENSIONS
